package edu.ufp.inf.sd.project.client.layouts;//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================

import edu.ufp.inf.sd.project.client.JobShopClient;
import edu.ufp.inf.sd.project.client.WorkerImpl;
import edu.ufp.inf.sd.project.server.auth.AuthFactoryRI;
import edu.ufp.inf.sd.project.server.session.UserSessionRI;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.concurrent.TimeoutException;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;

/**
 * @author Administrator
 * @created May 29, 2021
 */
public class createJobGroupLayout extends JFrame {
   static createJobGroupLayout thecreateJobGroupLayout;

   JPanel pnPanel0;
   JLabel lbLabelEstrategia;
   JLabel lbLabelCoins;
   JLabel lbLabelnameGroup;
   JButton btBut0;
   JTextField tfTextName;
   JTextField tfTextCoins;
   JTextField tfTextEst;
   JLabel lbLabelPath;
   JTextField tfTextPath;
   /**
    * private AuthFactoryRI authRI;
    * private UserSessionRI sessionRI;
    * /**
    */

   private static UserSessionRI sessionRI_static;
   private static JobShopClient JobShopClient_static;

   /**
    *
    */


   public static void createJobGroupLayoutcorrect(JobShopClient JobShopClient, String args[]) throws RemoteException {
      JobShopClient_static = JobShopClient;
      sessionRI_static = JobShopClient_static.getSessionRI();
      main(args);
   }


   public static void main(String args[]) {
      try {
         UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
      } catch (ClassNotFoundException e) {
      } catch (InstantiationException e) {
      } catch (IllegalAccessException e) {
      } catch (UnsupportedLookAndFeelException e) {
      }
      thecreateJobGroupLayout = new createJobGroupLayout();
   }


   /**
    *
    */
   public createJobGroupLayout() {
      super("TITLE");

      pnPanel0 = new JPanel();
      pnPanel0.setBorder(BorderFactory.createTitledBorder(""));
      GridBagLayout gbPanel0 = new GridBagLayout();
      GridBagConstraints gbcPanel0 = new GridBagConstraints();
      pnPanel0.setLayout(gbPanel0);

      lbLabelEstrategia = new JLabel("Estrategia");
      gbcPanel0.gridx = 0;
      gbcPanel0.gridy = 2;
      gbcPanel0.gridwidth = 1;
      gbcPanel0.gridheight = 1;
      gbcPanel0.fill = GridBagConstraints.BOTH;
      gbcPanel0.weightx = 1;
      gbcPanel0.weighty = 1;
      gbcPanel0.anchor = GridBagConstraints.NORTH;
      gbPanel0.setConstraints(lbLabelEstrategia, gbcPanel0);
      pnPanel0.add(lbLabelEstrategia);

      lbLabelCoins = new JLabel("Coins");
      gbcPanel0.gridx = 0;
      gbcPanel0.gridy = 1;
      gbcPanel0.gridwidth = 1;
      gbcPanel0.gridheight = 1;
      gbcPanel0.fill = GridBagConstraints.BOTH;
      gbcPanel0.weightx = 1;
      gbcPanel0.weighty = 1;
      gbcPanel0.anchor = GridBagConstraints.NORTH;
      gbPanel0.setConstraints(lbLabelCoins, gbcPanel0);
      pnPanel0.add(lbLabelCoins);

      lbLabelnameGroup = new JLabel("Nome do grupo");
      gbcPanel0.gridx = 0;
      gbcPanel0.gridy = 0;
      gbcPanel0.gridwidth = 1;
      gbcPanel0.gridheight = 1;
      gbcPanel0.fill = GridBagConstraints.BOTH;
      gbcPanel0.weightx = 1;
      gbcPanel0.weighty = 1;
      gbcPanel0.anchor = GridBagConstraints.NORTH;
      gbPanel0.setConstraints(lbLabelnameGroup, gbcPanel0);
      pnPanel0.add(lbLabelnameGroup);

      tfTextName = new JTextField();
      gbcPanel0.gridx = 1;
      gbcPanel0.gridy = 0;
      gbcPanel0.gridwidth = 1;
      gbcPanel0.gridheight = 1;
      gbcPanel0.fill = GridBagConstraints.BOTH;
      gbcPanel0.weightx = 1;
      gbcPanel0.weighty = 0;
      gbcPanel0.anchor = GridBagConstraints.NORTH;
      gbPanel0.setConstraints(tfTextName, gbcPanel0);
      pnPanel0.add(tfTextName);

      tfTextCoins = new JTextField();
      gbcPanel0.gridx = 1;
      gbcPanel0.gridy = 1;
      gbcPanel0.gridwidth = 1;
      gbcPanel0.gridheight = 1;
      gbcPanel0.fill = GridBagConstraints.BOTH;
      gbcPanel0.weightx = 1;
      gbcPanel0.weighty = 0;
      gbcPanel0.anchor = GridBagConstraints.NORTH;
      gbPanel0.setConstraints(tfTextCoins, gbcPanel0);
      pnPanel0.add(tfTextCoins);

      tfTextEst = new JTextField();
      gbcPanel0.gridx = 1;
      gbcPanel0.gridy = 2;
      gbcPanel0.gridwidth = 1;
      gbcPanel0.gridheight = 1;
      gbcPanel0.fill = GridBagConstraints.BOTH;
      gbcPanel0.weightx = 1;
      gbcPanel0.weighty = 0;
      gbcPanel0.anchor = GridBagConstraints.NORTH;
      gbPanel0.setConstraints(tfTextEst, gbcPanel0);
      pnPanel0.add(tfTextEst);

      btBut0 = new JButton("Sent");
      gbcPanel0.gridx = 2;
      gbcPanel0.gridy = 3;
      gbcPanel0.gridwidth = 1;
      gbcPanel0.gridheight = 1;
      gbcPanel0.fill = GridBagConstraints.BOTH;
      gbcPanel0.weightx = 1;
      gbcPanel0.weighty = 0;
      gbcPanel0.anchor = GridBagConstraints.NORTH;
      gbPanel0.setConstraints(btBut0, gbcPanel0);
      pnPanel0.add(btBut0);
      btBut0.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            try {
               btSent(evt);
            } catch (IOException | TimeoutException e) {
               e.printStackTrace();
            }
         }
      });

      lbLabelPath = new JLabel("Path");
      gbcPanel0.gridx = 0;
      gbcPanel0.gridy = 3;
      gbcPanel0.gridwidth = 1;
      gbcPanel0.gridheight = 1;
      gbcPanel0.fill = GridBagConstraints.BOTH;
      gbcPanel0.weightx = 1;
      gbcPanel0.weighty = 1;
      gbcPanel0.anchor = GridBagConstraints.NORTH;
      gbPanel0.setConstraints(lbLabelPath, gbcPanel0);
      pnPanel0.add(lbLabelPath);

      tfTextPath = new JTextField();
      gbcPanel0.gridx = 1;
      gbcPanel0.gridy = 3;
      gbcPanel0.gridwidth = 1;
      gbcPanel0.gridheight = 1;
      gbcPanel0.fill = GridBagConstraints.BOTH;
      gbcPanel0.weightx = 1;
      gbcPanel0.weighty = 0;
      gbcPanel0.anchor = GridBagConstraints.NORTH;
      gbPanel0.setConstraints(tfTextPath, gbcPanel0);
      pnPanel0.add(tfTextPath);

      setDefaultCloseOperation(EXIT_ON_CLOSE);

      setContentPane(pnPanel0);
      pack();
      setVisible(true);
   }


   private void btSent(java.awt.event.ActionEvent evt) throws IOException, TimeoutException {

      if (tfTextCoins.getText().compareTo("") != 0 && tfTextEst.getText().compareTo("") != 0 && tfTextName.getText().compareTo("") != 0 && tfTextPath.getText().compareTo("") != 0) {
         if (tfTextEst.getText().compareTo("ts") == 0 || tfTextEst.getText().compareTo("ga") == 0) {
            //String path = "edu/ufp/inf/sd/project/data/la04.txt";
            ///Só podemos criar um jobgroup se o plafon for inferior ao saldo
            if (Integer.parseInt(tfTextCoins.getText()) < sessionRI_static.showCoins()) {
               JobShopClient_static.setJobGroupRI(JobShopClient_static.getSessionRI().createJobGroup(tfTextName.getText(), Integer.parseInt(tfTextCoins.getText()), tfTextPath.getText(), tfTextEst.getText()));//tira ao saldo o plafon para o jobgroup
               JobShopClient_static.getCoinsPayment(-Integer.parseInt(tfTextCoins.getText()));
               if (JobShopClient_static.getJobGroupRI() != null) {
                  if (JobShopClient_static.getJobGroupRI().getCoins() == 10) {
                     WorkerImpl worker = new WorkerImpl(sessionRI_static.showMyUsername(), JobShopClient_static.getJobGroupRI(), JobShopClient_static);
                     JobShopClient_static.getJobGroupRI().verify_winner();
                  } else {
                     WorkerImpl worker = new WorkerImpl(sessionRI_static.showMyUsername(), JobShopClient_static.getJobGroupRI(), JobShopClient_static);
                  }

               }
            }

         }
      }
      dispose(); //sair da janela
   }
}