package edu.ufp.inf.sd.project.client.layouts;//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================

import edu.ufp.inf.sd.project.client.JobShopClient;

import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.rmi.RemoteException;
import javax.swing.JTextArea;
import javax.swing.JLabel;
import javax.swing.JButton;

/**
 * @author Administrator
 * @created May 22, 2021
 */
public class menucorrect extends JFrame {
    static menucorrect themenucorrect;

    JPanel pnPanel0;
    JTextArea taArea0;
    JLabel lbLabel0;
    JButton btSent;
    JButton btListexistinggroups;
    JButton btPauseexistinggroup;
    JButton btCreateGroupandattachworker;
    JButton btAttachworkertogroup;
    JButton btDeleteexistinggroup;
    JButton btContinueexistinggroup;
    JButton btAddCoins;
    JButton btMyCoins;
    JButton btListUsers;
    JButton btLogout;

    //private JobShopClient jobShopClient = new JobShopClient(args);

    /**
     *
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
        } catch (InstantiationException e) {
        } catch (IllegalAccessException e) {
        } catch (UnsupportedLookAndFeelException e) {
        }
        themenucorrect = new menucorrect();
    }

    /**
     *
     */
    public menucorrect() {
        super("Session:");

        pnPanel0 = new JPanel();
        GridBagLayout gbPanel0 = new GridBagLayout();
        GridBagConstraints gbcPanel0 = new GridBagConstraints();
        pnPanel0.setLayout(gbPanel0);

        taArea0 = new JTextArea(2, 10);
        gbcPanel0.gridx = 0;
        gbcPanel0.gridy = 6;
        gbcPanel0.gridwidth = 13;
        gbcPanel0.gridheight = 3;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 1;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(taArea0, gbcPanel0);
        pnPanel0.add(taArea0);

        lbLabel0 = new JLabel("DISPLAY:");
        gbcPanel0.gridx = 0;
        gbcPanel0.gridy = 0;
        gbcPanel0.gridwidth = 21;
        gbcPanel0.gridheight = 6;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 1;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(lbLabel0, gbcPanel0);
        pnPanel0.add(lbLabel0);


/******************************************************* BUTTOES *****************************************************/
        btSent = new JButton("sent");
        gbcPanel0.gridx = 13;
        gbcPanel0.gridy = 6;
        gbcPanel0.gridwidth = 3;
        gbcPanel0.gridheight = 3;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btSent, gbcPanel0);
        pnPanel0.add(btSent);
        btSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btSent(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });


        btListexistinggroups = new JButton("List existing groups");
        gbcPanel0.gridx = 0;
        gbcPanel0.gridy = 9;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 1;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btListexistinggroups, gbcPanel0);
        pnPanel0.add(btListexistinggroups);
        btListexistinggroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btListexistinggroups(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });


        btPauseexistinggroup = new JButton("Pause existing group");
        gbcPanel0.gridx = 0;
        gbcPanel0.gridy = 10;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btPauseexistinggroup, gbcPanel0);
        pnPanel0.add(btPauseexistinggroup);
        btPauseexistinggroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btPauseexistinggroup(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });

        btCreateGroupandattachworker = new JButton("Create Group and attach worker");
        gbcPanel0.gridx = 0;
        gbcPanel0.gridy = 12;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btCreateGroupandattachworker, gbcPanel0);
        pnPanel0.add(btCreateGroupandattachworker);
        btCreateGroupandattachworker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btCreateGroupandattachworker(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });

        btAttachworkertogroup = new JButton(" Attach worker to group");
        gbcPanel0.gridx = 0;
        gbcPanel0.gridy = 14;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btAttachworkertogroup, gbcPanel0);
        pnPanel0.add(btAttachworkertogroup);
        btAttachworkertogroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btAttachworkertogroup(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });


        btDeleteexistinggroup = new JButton("Delete existing group");
        gbcPanel0.gridx = 0;
        gbcPanel0.gridy = 16;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btDeleteexistinggroup, gbcPanel0);
        pnPanel0.add(btDeleteexistinggroup);
        btDeleteexistinggroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btDeleteexistinggroup(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });

        btContinueexistinggroup = new JButton("Continue existing group");
        gbcPanel0.gridx = 0;
        gbcPanel0.gridy = 18;
        gbcPanel0.gridwidth = 1;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btContinueexistinggroup, gbcPanel0);
        pnPanel0.add(btContinueexistinggroup);
        btContinueexistinggroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btContinueexistinggroup(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });


        btAddCoins = new JButton("Add Coins");
        gbcPanel0.gridx = 18;
        gbcPanel0.gridy = 18;
        gbcPanel0.gridwidth = 3;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btAddCoins, gbcPanel0);
        pnPanel0.add(btAddCoins);
        btAddCoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btAddCoins(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });

        btMyCoins = new JButton("My Coins");
        gbcPanel0.gridx = 18;
        gbcPanel0.gridy = 16;
        gbcPanel0.gridwidth = 3;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btMyCoins, gbcPanel0);
        pnPanel0.add(btMyCoins);

        btMyCoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btMyCoins(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });


        btListUsers = new JButton("List Users");
        gbcPanel0.gridx = 18;
        gbcPanel0.gridy = 14;
        gbcPanel0.gridwidth = 3;
        gbcPanel0.gridheight = 2;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btListUsers, gbcPanel0);
        pnPanel0.add(btListUsers);

        btListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btListUsers(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });

        btLogout = new JButton("Logout");
        gbcPanel0.gridx = 16;
        gbcPanel0.gridy = 6;
        gbcPanel0.gridwidth = 5;
        gbcPanel0.gridheight = 3;
        gbcPanel0.fill = GridBagConstraints.BOTH;
        gbcPanel0.weightx = 1;
        gbcPanel0.weighty = 0;
        gbcPanel0.anchor = GridBagConstraints.NORTH;
        gbPanel0.setConstraints(btLogout, gbcPanel0);
        pnPanel0.add(btLogout);
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btLogout(evt);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
        });


        setDefaultCloseOperation(EXIT_ON_CLOSE);

        setContentPane(pnPanel0);
        pack();
        setVisible(true);
    }
/***************************************fUNCOES****************************************************************/
    private void pnPanel0(java.awt.event.ActionEvent evt) throws RemoteException {
        taArea0.setText("empresa de chouriças");
    }

    private void taArea0(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void lbLabel0(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btSent(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btListexistinggroups(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btPauseexistinggroup(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btCreateGroupandattachworker(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btAttachworkertogroup(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btDeleteexistinggroup(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btContinueexistinggroup(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btAddCoins(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btMyCoins(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btListUsers(java.awt.event.ActionEvent evt) throws RemoteException {
    }

    private void btLogout(java.awt.event.ActionEvent evt) throws RemoteException {
    }

}